name: Demo
on:
  pull_request:
  push:
    branches:
      - master
      - demo
jobs:
  demo:
    - id: tmpCreds
      uses: ThinkThenRant/cert-2-aws-creds@dde1543
      with:
          certificate: ${{ secrets.CERTIFICATE }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          iot_endpoint: ${{ secrets.IOT_ENDPOINT }}
          aws_iot_role_alias: 'ThinkThenRant@cert-2-aws-creds'
    - name: Check whether we can call STS successfully
      run: aws sts get-caller-identity